/*
 * This file is generated by jOOQ.
 */
package org.anisation.jooqGenerated;


import org.anisation.jooqGenerated.tables.DatabaseEntity;
import org.anisation.jooqGenerated.tables.records.DatabaseEntityRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabaseEntityRecord> DATABASE_ENTITY_PKEY = UniqueKeys0.DATABASE_ENTITY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DatabaseEntityRecord> DATABASE_ENTITY_PKEY = Internal.createUniqueKey(DatabaseEntity.DATABASE_ENTITY, "database_entity_pkey", new TableField[] { DatabaseEntity.DATABASE_ENTITY.ID }, true);
    }
}
