/*
 * This file is generated by jOOQ.
 */
package org.anisation.jooqGenerated;


import org.anisation.jooqGenerated.tables.DatabaseEntity;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.database_entity</code>.
     */
    public static final DatabaseEntity DATABASE_ENTITY = DatabaseEntity.DATABASE_ENTITY;
}
