/*
 * This file is generated by jOOQ.
 */
package org.anisation.jooqGenerated.tables.records;


import org.anisation.jooqGenerated.tables.DatabaseEntity;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabaseEntityRecord extends UpdatableRecordImpl<DatabaseEntityRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -517859088;

    /**
     * Setter for <code>public.database_entity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.database_entity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.database_entity.text_field</code>.
     */
    public void setTextField(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.database_entity.text_field</code>.
     */
    public String getTextField() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.database_entity.number_field</code>.
     */
    public void setNumberField(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.database_entity.number_field</code>.
     */
    public Long getNumberField() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DatabaseEntity.DATABASE_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return DatabaseEntity.DATABASE_ENTITY.TEXT_FIELD;
    }

    @Override
    public Field<Long> field3() {
        return DatabaseEntity.DATABASE_ENTITY.NUMBER_FIELD;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTextField();
    }

    @Override
    public Long component3() {
        return getNumberField();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTextField();
    }

    @Override
    public Long value3() {
        return getNumberField();
    }

    @Override
    public DatabaseEntityRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatabaseEntityRecord value2(String value) {
        setTextField(value);
        return this;
    }

    @Override
    public DatabaseEntityRecord value3(Long value) {
        setNumberField(value);
        return this;
    }

    @Override
    public DatabaseEntityRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatabaseEntityRecord
     */
    public DatabaseEntityRecord() {
        super(DatabaseEntity.DATABASE_ENTITY);
    }

    /**
     * Create a detached, initialised DatabaseEntityRecord
     */
    public DatabaseEntityRecord(Long id, String textField, Long numberField) {
        super(DatabaseEntity.DATABASE_ENTITY);

        set(0, id);
        set(1, textField);
        set(2, numberField);
    }
}
